import { Space_Mono } from "next/font/google";
import "./globals.css";

const spaceMono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Tip calculator",
  description: "Generated by a tip result",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`flex justify-center items-center bg-light-green md:px-4 lg:px-5 ${spaceMono.className}`}
      >
        {children}
      </body>
    </html>
  );
}
